import AVFoundation
import Darwin
import Foundation
import LTX25Engine

/// Weight-free source preparation for frozen-audio A2V. Both
/// files contain decoded source samples; neither is generated by the model.
public struct MLXSourceAudioInterval: Sendable {
  public struct Prepared: Sendable {
    public let publication: URL
    public let conditioning: URL
    public let sourceStartSeconds: Double
    public let durationSeconds: Double
    public let publicationSamples: Int
    public let conditioningSamples: Int
  }
  public let source: URL
  public let sourceStartSeconds: Double
  public let sourceDurationSeconds: Double?
  public let durationSeconds: Double
  private let signature: [Int64]

  public init(source: URL, sourceStartSeconds: Double, sourceDurationSeconds: Double? = nil, durationSeconds: Double) throws {
    guard source.isFileURL, source.path.hasPrefix("/"), !source.path.utf8.contains(0),
      sourceStartSeconds.isFinite, (0...86400).contains(sourceStartSeconds),
      durationSeconds.isFinite, (0.001...30.1).contains(durationSeconds),
      sourceDurationSeconds == nil || (sourceDurationSeconds!.isFinite && (0.001...86400).contains(sourceDurationSeconds!)) else {
      throw LTXError.invalid("A2V source needs an absolute local audio file, a finite nonnegative in-point, and 0.001–30 seconds of output.")
    }
    let resolved = source.standardizedFileURL.resolvingSymlinksInPath()
    self.source = resolved
    self.sourceStartSeconds = sourceStartSeconds
    self.sourceDurationSeconds = sourceDurationSeconds
    self.durationSeconds = durationSeconds
    signature = try Self.fileSignature(resolved)
  }
  private static func fileSignature(_ url: URL) throws -> [Int64] {
    var value = stat()
    guard url.path.withCString({ Darwin.lstat($0, &value) }) == 0,
      value.st_mode & S_IFMT == S_IFREG, value.st_size > 0,
      FileManager.default.isReadableFile(atPath: url.path) else {
      throw LTXError.invalid("A2V source must be a readable regular media file.")
    }
    return [Int64(value.st_dev), Int64(bitPattern: UInt64(value.st_ino)), value.st_size,
      Int64(value.st_mtimespec.tv_sec), Int64(value.st_mtimespec.tv_nsec),
      Int64(value.st_ctimespec.tv_sec), Int64(value.st_ctimespec.tv_nsec)]
  }
  private func verify() throws {
    guard try Self.fileSignature(source) == signature else {
      throw LTXError.invalid("A2V source changed during preparation. Prepare the clip again.")
    }
  }
  public func extract(ffmpeg: URL, directory: URL) async throws -> Prepared {
    try verify(); try Task.checkCancellation()
    guard ffmpeg.isFileURL, FileManager.default.isExecutableFile(atPath: ffmpeg.path),
      directory.isFileURL, !FileManager.default.fileExists(atPath: directory.path) else {
      throw LTXError.invalid("A2V preparation requires FFmpeg and a new local output directory.")
    }
    let asset = AVURLAsset(url: source)
    guard let track = try await asset.loadTracks(withMediaType: .audio).first else {
      throw LTXError.invalid("A2V source has no audio track.")
    }
    let descriptions = try await track.load(.formatDescriptions)
    guard let format = descriptions.first, CMFormatDescriptionGetMediaType(format) == kCMMediaType_Audio,
      let stream = CMAudioFormatDescriptionGetStreamBasicDescription(format),
      (1...2).contains(stream.pointee.mChannelsPerFrame) else {
      throw LTXError.invalid("A2V source must have mono or stereo audio.")
    }
    let length = try await asset.load(.duration).seconds
    guard length.isFinite, sourceStartSeconds < length - 1e-6,
      sourceDurationSeconds == nil || sourceStartSeconds + sourceDurationSeconds! <= length + 0.01 else {
      throw LTXError.invalid("A2V source in-point is outside the audio file.")
    }
    let publicationSamples = Int((durationSeconds * 48000).rounded(.toNearestOrEven))
    let conditioningSamples = Int((durationSeconds * 16000).rounded(.toNearestOrEven))
    let parent = directory.deletingLastPathComponent()
    try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
    let staging = parent.appendingPathComponent(".audio-prepare-" + UUID().uuidString)
    try FileManager.default.createDirectory(at: staging, withIntermediateDirectories: false)
    defer { try? FileManager.default.removeItem(at: staging) }
    let publication = staging.appendingPathComponent("publication.wav")
    let conditioning = staging.appendingPathComponent("conditioning.wav")
    let channels = stream.pointee.mChannelsPerFrame == 1 ? "pan=stereo|c0=c0|c1=c0," : ""
    let trim = sourceDurationSeconds.map { ":duration=\($0)" } ?? ""
    let shared = "[0:a:0]atrim=start=\(sourceStartSeconds)\(trim),asetpts=PTS-STARTPTS,\(channels)asplit=2[pub][cond];"
    let pub = "[pub]aresample=48000,apad=whole_len=\(publicationSamples),atrim=end_sample=\(publicationSamples)[pubout];"
    let cond = "[cond]aresample=16000,apad=whole_len=\(conditioningSamples),atrim=end_sample=\(conditioningSamples)[condout]"
    let log = staging.appendingPathComponent("ffmpeg.log")
    guard FileManager.default.createFile(atPath: log.path, contents: nil) else {
      throw LTXError.invalid("Cannot create A2V preparation log.")
    }
    let handle = try FileHandle(forWritingTo: log)
    defer { try? handle.close() }
    let process = Process()
    process.executableURL = ffmpeg
    process.arguments = ["-v", "error", "-nostdin", "-n", "-i", source.path,
      "-filter_complex", shared + pub + cond,
      "-map", "[pubout]", "-ac", "2", "-c:a", "pcm_f32le", publication.path,
      "-map", "[condout]", "-ac", "2", "-c:a", "pcm_f32le", conditioning.path]
    process.standardOutput = handle; process.standardError = handle
    try Task.checkCancellation(); try process.run()
    defer {
      if process.isRunning { process.terminate(); usleep(100_000)
        if process.isRunning { kill(process.processIdentifier, SIGKILL) } }
      process.waitUntilExit()
    }
    while process.isRunning { try Task.checkCancellation(); usleep(10_000) }
    guard process.terminationStatus == 0,
      FileManager.default.fileExists(atPath: publication.path),
      FileManager.default.fileExists(atPath: conditioning.path) else {
      throw LTXError.invalid("FFmpeg could not extract the selected A2V source interval.")
    }
    try Task.checkCancellation(); try verify()
    try FileManager.default.moveItem(at: staging, to: directory)
    return Prepared(publication: directory.appendingPathComponent("publication.wav"),
      conditioning: directory.appendingPathComponent("conditioning.wav"),
      sourceStartSeconds: sourceStartSeconds, durationSeconds: durationSeconds,
      publicationSamples: publicationSamples, conditioningSamples: conditioningSamples)
  }
}
