// swift-tools-version: 6.0
import PackageDescription

let package = Package(
  name: "WeeToddInference",
  platforms: [.macOS(.v14)],
  products: [
    .executable(name: "WeeToddLTXPerformanceProbe", targets: ["WeeToddLTXPerformanceProbe"]),
    .executable(name: "WeeToddInference", targets: ["WeeToddInference"]),
    .executable(name: "WeeToddLTXBlockProbe", targets: ["WeeToddLTXBlockProbe"]),
    .executable(name: "WeeToddLTXStackProbe", targets: ["WeeToddLTXStackProbe"]),
    .executable(name: "WeeToddLTXDenoiserProbe", targets: ["WeeToddLTXDenoiserProbe"]),
    .executable(name: "WeeToddLTXSamplingProbe", targets: ["WeeToddLTXSamplingProbe"]),
    .executable(name: "WeeToddLTXPipelineProbe", targets: ["WeeToddLTXPipelineProbe"]),
    .library(name: "TensorIO", targets: ["TensorIO"]),
    .library(name: "InferenceMedia", targets: ["InferenceMedia"]),
    .library(name: "InferenceContracts", targets: ["InferenceContracts"]),
    .library(name: "InferenceHost", targets: ["InferenceHost"]),
    .library(name: "LTX25Engine", targets: ["LTX25Engine"]),
    .library(name: "LTX25NNC", targets: ["LTX25NNC"]),
    .library(name: "LTX25Text", targets: ["LTX25Text"]),
    .library(name: "LTX25Video", targets: ["LTX25Video"]),
    .library(name: "LTX25Audio", targets: ["LTX25Audio"]),
    .library(name: "AdapterRuntime", targets: ["AdapterRuntime"]),
  ],
  dependencies: [.package(url: "https://github.com/liuliu/s4nnc.git",
    revision: "c99e45ad0d16c902c6c477e4dc9f1a7e49386dcd")],
  targets: [
    .target(name: "LTX25Text", dependencies: ["TensorIO"]),
    .target(name: "LTX25Video", dependencies: ["TensorIO"]),
    .target(name: "LTX25Audio", dependencies: ["TensorIO"]),
    .testTarget(name: "WeeToddLTXPipelineProbeTests", dependencies: ["WeeToddLTXPipelineProbe", "LTX25Audio"]),
    .testTarget(name: "LTX25TextTests", dependencies: ["LTX25Text", "InferenceTestSupport"], resources: [.copy("Fixtures")]),
    .testTarget(name: "LTX25VideoTests", dependencies: ["LTX25Video", "InferenceTestSupport"], resources: [.copy("Fixtures")]),
    .testTarget(name: "LTX25AudioTests", dependencies: ["LTX25Audio", "InferenceTestSupport"]),
    .executableTarget(name: "WeeToddLTXPerformanceProbe", dependencies: ["TensorIO", "LTX25NNC"]),
    .executableTarget(name: "WeeToddInference", dependencies: ["TensorIO", "LTX25Engine"]),
    .executableTarget(name: "WeeToddLTXBlockProbe", dependencies: ["TensorIO", "LTX25NNC"]),
    .executableTarget(name: "WeeToddLTXStackProbe", dependencies: ["TensorIO", "LTX25NNC"]),
    .executableTarget(name: "WeeToddLTXDenoiserProbe", dependencies: ["TensorIO", "LTX25NNC"]),
    .executableTarget(name: "WeeToddLTXSamplingProbe", dependencies: ["TensorIO", "LTX25NNC", "LTX25Engine"]),
    .executableTarget(name: "WeeToddLTXPipelineProbe", dependencies: ["InferenceMedia", "AdapterRuntime", "LTX25Text", "LTX25NNC", "LTX25Engine", "LTX25Video", "LTX25Audio"]),
    .target(name: "LTX25NNC", dependencies: ["AdapterRuntime", "TensorIO", "LTX25Engine", "LTX25Video",
      .product(name: "NNC", package: "s4nnc")]),
    .testTarget(name: "LTX25NNCTests", dependencies: ["AdapterRuntime", "LTX25NNC", "InferenceTestSupport"], resources: [.copy("Fixtures")]),
    .target(name: "TensorIO"),
    .target(name: "InferenceMedia"),
    .testTarget(name: "InferenceMediaTests", dependencies: ["InferenceMedia"]),
    .target(name: "InferenceContracts"),
    .testTarget(name: "InferenceContractsTests", dependencies: ["InferenceContracts"]),
    .target(name: "InferenceHost"),
    .target(name: "AdapterRuntime", dependencies: ["TensorIO"]),
    .target(name: "InferenceTestSupport", path: "Tests/Support"),
    .testTarget(name: "AdapterRuntimeTests", dependencies: ["AdapterRuntime", "InferenceTestSupport"]),
    .target(name: "LTX25Engine", dependencies: ["TensorIO", "AdapterRuntime"], resources: [.copy("Shaders")]),
    .testTarget(name: "LTX25EngineTests", dependencies: ["LTX25Engine", "InferenceTestSupport"]),
    .testTarget(name: "InferenceHostTests", dependencies: ["InferenceHost"]),
    .testTarget(name: "TensorIOTests", dependencies: ["TensorIO", "InferenceTestSupport"]),
  ],
  swiftLanguageModes: [.v6]
)
